1. lépés: Importálom az adatokat a pandas package segítségével

In [2]:
from sdv.demo import load_tabular_demo
import pandas as pd

data = pd.read_csv('horse.csv')

data.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,...,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,74.0,7.4,NaN,NaN,died,no,4300,0,0,no

In [4]:
from sdv.tabular import GaussianCopula

model = GaussianCopula(primary_key='hospital_number')
model.fit(data)

sample = model.sample(200)
sample.head()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,yes,adult,0,38.7,96.0,55.0,cold,NaN,pale_cyanotic,more_3_sec,...,NaN,NaN,NaN,NaN,lived,yes,6355,154,45,no
1,no,adult,1,37.7,62.0,NaN,cool,normal,pale_pink,less_3_sec,...,42.6,6.8,serosanguious,NaN,lived,yes,10270,241,45,yes
2,no,adult,2,38.7,71.0,21.0,cool,normal,pale_pink,less_3_sec,...,25.3,12.3,serosanguious,3.6,lived,yes,5564,973,174,yes
3,yes,adult,3,37.6,105.0,NaN,cool,reduced,normal_pink,NaN,...,38.5,NaN,NaN,5.3,lived,yes,11532,99,68,no
4,yes,adult,4,38.4,94.0,26.0,NaN,normal,normal_pink,less_3_sec,...,44.9,13.2,NaN,NaN,euthanized,yes,8511,422,44,no

Kiértékelés:

In [10]:
from sdv.evaluation import evaluate

evaluate(sample, data, metrics=['CSTest','KSComplement'], aggregate=False)

,metric,name,raw_score,normalized_score,min_value,max_value,goal,error
0,CSTest,Chi-Squared,0.978743,0.978743,0.0,1.0,MAXIMIZE,None
1,KSComplement,Inverted Kolmogorov-Smirnov D statistic,0.542575,0.542575,0.0,1.0,MAXIMIZE,None